### PR TITLE
Fix httptests and nettests segfault issue

### PR DESCRIPTION
**Pull request by Malesio**
Hi back Kam,

I think I've finally found out `httptests` and `nettests` segfault issue. Since `net::dns::resolve` runs asynchronously, `callback` parameter goes out of scope before DNS resolution callback could have been called, hence the reference to `callback` becoming invalid in said callback, causing it to UB. Changing from capture-by-reference to capture-by-value in `createRequest` callback lambda does actually work. We could also capture the callback only, it's up to you then.

I've fixed hardcoded `sockaddr*` length too, as dealing with IPv6 addresses will cause `Address` class to fail parsing (should use `ai_addrlen` field instead).

I've also made a few changes in the `AbstractDelegate` and `Slot` classes, since I ran into some memory leaks shown by Valgrind, caused by dynamic allocs of `FunctionDelegate`s and `ClassDelegate`s which aren't freed.
Valgrind also revealed leaks in `addReceiver` method of `SocketAdapter` class, however I don't know where it could come from, as the only pointer involved in here is `new Ref`, which seems to be freed in `cleanupReceivers`.

I could have split this in several PRs though, sorry for that big one.

### CODE REVIEW

**Comment by Malesio** [comment]
Alright, using `std::shared_ptr<Ref>` instead of raw pointers seems to get rid of 'critical leaks', aka 'definitely lost', according to Valgrind. This is far less significant, though.

**Comment by auscaster** [comment]
Thanks very much for your fixes. 

Had no idea the dns::resolve was hardcoded to sourcey.com after a recent commit. Again, thanks so much!

**Comment by auscaster** [comment]
Also regarding the `net::dns::resolve` callback going out of scope, I updated the socket class a few days ago to pass in a shared context which holds the pointer until the callback returns.

**Comment by auscaster** [comment]
All tests pass. Nice work

**Pull request merged**
